version: "3.5"

services:
    backend:
        image: mocap/backend
        container_name: mocap-backend
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env.production
            - .env.production.local
        networks:
            - mocap
        ports:
            - 8000:8080
        restart: always
        command: java -jar app.jar
networks:
    mocap:
        external: true
