frontend:
    uri: "${FRONTEND_URI}"

server:
    servlet:
        context-path: "/"
    port: "8080"

keycloak:
    uri: "http://mocap-keycloak:8080"
    realm: "mocap-dev"
    clientId: "mocap-backend"

docker:
    host: "unix:///var/run/docker.sock"
    tempDockerfileDir: "/app/temp/dockerfiles"
    tempSourceDir: "/app/temp/sources"

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "${keycloak.uri}/realms/${keycloak.realm}"
                    jwk-set-uri: "${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs"
    datasource:
        mocap:
            url: "jdbc:postgresql://mocap-database:5432/mocap"
            username: "${DATABASE_USERNAME}"
            password: "${DATABASE_PASSWORD}"
        keycloak:
            url: "jdbc:postgresql://mocap-database:5432/keycloak"
            username: "${DATABASE_USERNAME}"
            password: "${DATABASE_PASSWORD}"
            schema: public
    jpa:
        hibernate:
            ddl-auto: "update"
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQLDialect"
                default_schema: "public"
    mail:
        host: "smtp.office365.com"
        port: 587
        username: "${EMAIL_USERNAME}"
        password: "${EMAIL_PASSWORD}"
        properties:
            mail:
                smtp:
                    timeout: 5000
                    writetimeout: 5000
                    connecttimeout: 5000
                    auth: true
                    starttls:
                        enable: true
