frontend:
    uri: "${FRONTEND_URI}"

server:
    servlet:
        context-path: "/"
    port: "8080"

logging:
    level:
        com:
            mocaphk:
                backend: "DEBUG"

keycloak:
    uri: "http://localhost:8888"
    realm: "mocap-dev"
    clientId: "mocap-backend"

spring:
    security:
        # disable security for testing
        basic:
            enabled: false
    datasource:
        mocap:
            url: "jdbc:postgresql://localhost:5432/mocap"
            username: "${DATABASE_USERNAME}"
            password: "${DATABASE_PASSWORD}"
        keycloak:
            url: "jdbc:postgresql://localhost:5432/keycloak"
            username: "${DATABASE_USERNAME}"
            password: "${DATABASE_PASSWORD}"
            schema: public
    jpa:
        hibernate:
            ddl-auto: "update"
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQLDialect"
                default_schema: "test"
    mail:
        host: "smtp.office365.com"
        port: 587
        username: "${EMAIL_USERNAME}"
        password: "${EMAIL_PASSWORD}"
        properties:
            mail:
                smtp:
                    timeout: 5000
                    writetimeout: 5000
                    connecttimeout: 5000
                    auth: true
                    starttls:
                        enable: true
